apiVersion: v1
kind: Service
metadata:
   name: py-app-svc
   namespace: prod
spec:
   type: NodePort
   selector:
      app: python-app
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001
