apiVersion: v1
kind: Service
metadata:
   name: py-app-svc
   namespace: prod
spec:
  type: LoadBalancer
  selector:
      app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
