apiVersion: v1
kind: Service
metadata:
   name: py-app-svc
   namespace: prod
spec:
  selector:
      app: python-app
  type: NodePort    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 33333
