apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
spec:
  project: default  # Name of the ArgoCD project to which this app belongs
  source:
    repoURL: https://github.com/R8ghid/python_sample_app.git  # URL of your Git repository
    targetRevision: HEAD  # Git branch, tag, or commit SHA to deploy
    path: argocd  # Path within the Git repository (root in this example)
    # helm:
    #   valueFiles:
    #     - values.yaml  # Helm values file if you are using Helm (optional)
  destination:
    server: 'https://kubernetes.default.svc'  # Kubernetes API server address
    namespace: default  # Namespace where your application will be deployed
  syncPolicy:
    automated:
      prune: true  # Prune resources that are not in the Git repository (optional)
      selfHeal: true  # Automatically reconcile differences between Git and cluster
    syncOptions:
      - Validate=false  # Additional sync options if needed (optional)

